website:
  urls: https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/inowroclaw?distanceRadius=0&market=ALL&priceMax=200000&locations=%5Bcities_6-2496%5D&viewType=listing&lang=pl&searchingCriteria=sprzedaz&searchingCriteria=mieszkanie&searchingCriteria=cala-polska&limit=72&page=1
  parent_xpath: /html/body/div[1]/div[1]/main/div[1]/div[3]/div[1]/div[2]
